---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner:  morad
    group:  morad
    mode: 0640
  when: nginx_yum_repo_enabled | bool
  
- name: Ensure nginx is installed.
  become: true
  package:
    name: "{{ nginx_package_name }}"
    state: present
