variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}
variable "name" {}
variable "location" {}
variable "owner" {}
variable "version" {}
variable "name_vnet" {}
variable "add_space" {
  type = "list"
}
variable "name_subnet2" {}
variable "add_prefix1" {}
variable "add_prefix2" {}
variable "name_pubIp1" {}
variable "name_nsg2" {}
variable "allocation_method" {}
variable "nameNIC3" {}
variable "nameNIC4" {}
variable "nameNICconfig3" {}
variable "nameNICconfig4" {}
variable "nameVM3" {}
variable "nameVM4" {}
variable "vmSize2" {}
variable "keyData" {}
variable "computer_name3" {}
variable "computer_name4" {}
